mysqlInnodbcluster:
  serverInstances: 1
  routerInstances: 1

  tls:
    useSelfSigned: true

  credentials:
    root:
      host: "%"
      user: "root"
      password: "root"

  envSecret:
    GPAS_USER: "" # value set by externalSecret
    GPAS_PASSWORD: "" # value set by externalSecret
    GICS_USER: "" # value set by externalSecret
    GICS_PASSWORD: "" # value set by externalSecret
    EPIX_USER: "" # value set by externalSecret
    EPIX_PASSWORD: "" # value set by externalSecret

  secretName: ttp-mysql-secret-ref-external
  externalSecret:
    enabled: true
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    dataFrom:
      extract:
        key: ttp-mysql-secret-ref-external

  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi