mysqlInnodbcluster:
  serverInstances: 1
  routerInstances: 1

  tls:
    useSelfSigned: true

  credentials:
    root:
      host: "%"
      user: "root"
      password: "root"

  envSecret:
    GPAS_USER: "gpas_user" # preferably leave empty and set as externalSecret
    GPAS_PASSWORD: "gpas_password" # preferably leave empty and set as externalSecret
    GICS_USER: "gics_user" # preferably leave empty and set as externalSecret
    GICS_PASSWORD: "gics_password" # preferably leave empty and set as externalSecret
    EPIX_USER: "epix_user" # preferably leave empty and set as externalSecret
    EPIX_PASSWORD: "epix_password" # preferably leave empty and set as externalSecret

  secretName: ttp-mysql-secret-ref
  externalSecret:
    enabled: false

  persistence:
    enabled: true
    storageClass: ""
    size: 1Gi